//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupAccess
    {
        public string ModuleID { get; set; }
        public string MenuID { get; set; }
        public string GroupID { get; set; }
        public Nullable<bool> ButtonAdd { get; set; }
        public Nullable<bool> ButtonUpdate { get; set; }
        public Nullable<bool> ButtonDelete { get; set; }
        public Nullable<bool> ButtonPrint { get; set; }
    }
}
