//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Book
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> SchoolID { get; set; }
        public Nullable<System.Guid> ClassID { get; set; }
        public string Name { get; set; }
        public string Subject { get; set; }
        public string Type { get; set; }
        public string Price { get; set; }
        public string Description { get; set; }
        public string Condition { get; set; }
        public string Status { get; set; }
        public string Username { get; set; }
    }
}
